### ISSUE TITLE
Documentation issue regarding rar2fs

### ISSUE THREAD

**Issue by KyleSanderson** [JohnDoee/autotorrent2#19]
hi JohnDoee,

Thank you very much for continuing to work on this. I saw a comment in the config example file that I wanted to point out I have a very different view on. Specifically around this line https://github.com/JohnDoee/autotorrent2/blob/f89d4285d7256c5c3cf8b8bc779af04ac0e8b10f/config.example.toml#L30

Some sources prefer to extract their linux isos, and others prefer to have the original files from source. Clearly going from extracted back to the archive is a couple extra steps and less straight forward, but if scanning to find the extracted path, and matching on the fuse filesystem works that's excellent and further reduces fragmentation. At this point we have the data on disk, but it will not be in the client.

Not sure if this is the wrong viewpoint, if this is a documentation bug, or perhaps a scenario not considered. What do you think?

**Comment by JohnDoee** [comment]
I am not exactly sure what you are really asking here.

What that specific feature is used for is to avoid double indexing stuff like `.nfo` as it otherwise just works as a normal path on your disk.
