### ISSUE TITLE
Create an option to add torrents in a paused or stopped state

### ISSUE THREAD

**Issue by newadventure079** [JohnDoee/autotorrent2#20]
I have `fast_resume` set to `false` but if there is missing data, rtorrent will automatically start downloading the missing data into my at2 symlinks folder.  I would like the torrents to be set to paused or stopped so I can do my own hash check, and if the hash check is not 100%, I can change the save dir to be the actual data dir so the missing data is downloaded where the actual data resides and not my at2 symlinks folder.  This will solve the issue of having folders with at2 symlinks and actual data.

**Comment by JohnDoee** [comment]
Added in 1.2.0
