### ISSUE TITLE
Change "OK" to "Added"

### ISSUE THREAD

**Issue by newadventure079** [JohnDoee/autotorrent2#23]
When a torrent is added, the status is `OK`.  Changing it to `Added` puts it in line with the rest of the status verbs `Missing`, `Seeded`, `Failed`, etc.  Also, the summary at the end says `Added`

**Comment by JohnDoee** [comment]
Makes sense. It is "OK" only because that what it was in V1.

**Comment by JohnDoee** [comment]
Changed in 1.2.0
