### ISSUE TITLE
Pack into Shiv to simplify distribution?

### ISSUE THREAD

**Issue by si14** [JohnDoee/autotorrent2#25]
Hey Anders!

Do you think it's worth it to try and pack autotorrent2 into a [Shiv](https://github.com/linkedin/shiv) binary? Run on CI, it should make installation and use much easier.

**Comment by JohnDoee** [comment]
Sounds fine, it'll be part of a bigger automated release setup #26

**Comment by JohnDoee** [comment]
Next release will have a bunch of artifacts.
