### ISSUE TITLE
[Feature Request] Add {tracker name} variable for use in store_path

### ISSUE THREAD

**Issue by varoOP** [JohnDoee/autotorrent2#28]
It would be great to be able to save the links in tracker subfolders. Especially if two trackers happen to have same torrent name, it will be possible to avoid an error.

**Comment by JohnDoee** [comment]
There are three ways to do that, which one do you have in mind?

* "Source" key taken from the .torrent file
* Specify via commandline when running autotorrent, e.g. at2 add --variable tracker=linuxisoglobal
* Torrent tracker name taken from announce, can often be a domain name unrelated to the actual tracker

**Comment by varoOP** [comment]
Could users map tracker url to tracker name in the configuration file? This way, we can use this option 
> Torrent tracker name taken from announce, can often be a domain name unrelated to the actual tracker

And have it converted to whatever name is preferred. All torrents will have at least one tracker url so that is reliable in my opinion.

This has the con of users having to configure their tracker URLs. If you feel that would not be ideal then in my opinion 
>"Source" key taken from the .torrent file

This option is great too.

> Specify via commandline when running autotorrent, e.g. at2 add --variable tracker=linuxisoglobal

Can this option be added regardless? It will override no matter what is in the .torrent file.

**Comment by JohnDoee** [comment]
Fixed in 1.2.1
