### ISSUE TITLE
[Feature Request] Ability to disable json dump and torrent file link

### ISSUE THREAD

**Issue by varoOP** [JohnDoee/autotorrent2#32]
The default behavior of at2 is to create a folder `store_path/data` and hardlink torrent data to it. While a json file and the torrent file itself is saved to `store_path/`.

My request is to add a configuration option which would just link torrent data to `store_path/` and not dump the json file or save the torrent file.

**Comment by newadventure079** [comment]
I agree

**Comment by JohnDoee** [comment]
Fixed in 1.2.3
