### ISSUE TITLE
[Feature request] Move torrents 

### ISSUE THREAD

**Issue by koolmon10** [JohnDoee/autotorrent2#47]
It would be nice to be able to move torrents with this. I use hardlinks with my media library and end up with torrents that are no longer linked to my library files after various upgrades and other things, but I would like to continue seeding. These torrents I want to move to a different volume so they don't take up my library space.

**Comment by JohnDoee** [comment]
Most (all?) torrent clients supports that natively, not sure autotorrent would help here?
