### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by IITYWYBMAB** [JohnDoee/autotorrent2#57]
I haven't seen any updates in quite some time, just curious if it's worth looking at for my stack.

Thanks!

**Comment by JohnDoee** [comment]
What kind of updates do you hope for?

The project is largely complete with what I need personally and the bittorrent world is not moving at all. I also use it myself every day in my own pipeline.

**Comment by IITYWYBMAB** [comment]
OK, just want to be sure it's keeping up with the other related projects and keeping compatibility as they're updated.   Plus you have a to-do, which is indicative of continuing work.
