### ISSUE TITLE
ignore_files option is missing from config

### ISSUE THREAD

**Issue by newadventure079** [JohnDoee/autotorrent2#7]
It would be nice to have an option to ignore files and keep with at1 parity

A scan with at1 for my files would take 10 mins.  With at2, it takes 60 mins.  It might be because ignore_files is missing (I had a lot ignored with at1)

**Comment by JohnDoee** [comment]
The scan stuff might be slower too.

How long does something like `ls -R` take ? Does subsequent scans run faster (where most files are already saved to the database).

The OS sometimes caches file listings that might affect any tests and speed might depend on their order.

**Comment by newadventure079** [comment]
Subsequent scans are 15 mins faster:

`time at2 -v scan`
Executed in   45.24 mins

`ls -R` output:
`time ls -R "/dir1" "/dir2" "/dir3" "/dir4" "/dir5" "/dir6"`
Executed in  406.76 sec

I made some crude changes in `db.py`
```
if '.jpg' in name or '.png' in name or '.gif' in name:
    return
```

Time after crude image files ignore code:
`time at2 -v scan`
Executed in  733.14 secs

**Comment by JohnDoee** [comment]
Skip file pattern is added in 1.0.3
